import { routing } from "@/libs/i18n/routing";

import { Geist, Geist_Mono } from "next/font/google";
import { notFound } from "next/navigation";
import type React from "react";

import { ReactQueryProvider } from "@/libs/react-query/provider";
import { ThemeProviders } from "@/libs/theme/provider";
import { Theme } from "@/libs/theme/types";
import "@/styles/globals.css";
import { Metadata, Viewport } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { cookies } from "next/headers";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { SessionStorageKeys } from "@/constants/keys";
import { Language } from "@/libs/i18n/types";
import LivePreview from "@/components/live-preview";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  metadataBase: new URL(process.env.SITE_URL ?? "http://localhost:3000"),
  title: "Vindas",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as Language)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages({ locale: locale as Language });

  const cookieStore = await cookies();
  const theme = (cookieStore.get(SessionStorageKeys.THEME)?.value as Theme) || Theme.LIGHT;

  return (
    <html
      lang={locale}
      className={theme}
      style={{ colorScheme: theme }}
      suppressHydrationWarning
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReactQueryProvider>
          <NextIntlClientProvider messages={messages}>
            <ThemeProviders theme={theme}>
              <LivePreview />
              <main className="mx-auto min-h-screen max-w-5xl bg-white px-4 dark:bg-neutral-900">
                <ToastContainer
                  position="top-right"
                  autoClose={3000}
                  hideProgressBar={false}
                  newestOnTop
                  closeOnClick
                  pauseOnFocusLoss
                  draggable
                  pauseOnHover
                />
                {children}
              </main>
            </ThemeProviders>
          </NextIntlClientProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}
